name: CI-docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '!docs/code/**'
      - '.github/workflows/CI-docs.yml'

permissions: read-all

jobs:
  docs-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r docs/requirements.txt
      - name: html
        run: |
          make -C docs html
      - name: linkcheck
        run: |
          make -C docs linkcheck
