name: CI-docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '!docs/code/**'
      - '.github/workflows/CI-docs.yml'

permissions: read-all

jobs:
  docs-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r docs/requirements.txt
      - name: html
        run: |
          make -C docs html
      - name: linkcheck
        run: |
          make -C docs linkcheck
