name: CI-unix

on:
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!src/win/**'
      - '!.**'
      - '.github/workflows/CI-unix.yml'
  push:
    branches:
      - v[0-9].*
      - master

jobs:
  build-cross-qemu:
    runs-on: ubuntu-24.04
    name: build-cross-qemu-${{ matrix.config.arch }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {arch: arm,       triple: arm-linux-gnueabi,          qemu: arm,      }
          - {arch: armhf,     triple: arm-linux-gnueabihf,        qemu: arm,      }
          - {arch: aarch64,   triple: aarch64-linux-gnu,          qemu: aarch64,  }
          - {arch: riscv64,   triple: riscv64-linux-gnu,          qemu: riscv64,  }
          - {arch: ppc,       triple: powerpc-linux-gnu,          qemu: ppc,      }
          - {arch: ppc64,     triple: powerpc64-linux-gnu,        qemu: ppc64,    }
          - {arch: ppc64le,   triple: powerpc64le-linux-gnu,      qemu: ppc64le,  }
          - {arch: s390x,     triple: s390x-linux-gnu,            qemu: s390x,    }
          - {arch: mips,      triple: mips-linux-gnu,             qemu: mips,     }
          - {arch: mips64,    triple: mips64-linux-gnuabi64,      qemu: mips64,   }
          - {arch: mipsel,    triple: mipsel-linux-gnu,           qemu: mipsel,   }
          - {arch: mips64el,  triple: mips64el-linux-gnuabi64,    qemu: mips64el, }

    steps:
      - uses: actions/checkout@v6
      - name: Install qemu and gcc-${{ matrix.config.triple }}
        run: |
          sudo apt update
          sudo apt install ninja-build qemu-user qemu-user-binfmt gcc-${{ matrix.config.triple }} patchelf -y
          # QEMU developers have been arguing for years if they want to work around this glibc bug
          # so we will just implement our own workaround for it
          # https://bugs.launchpad.net/qemu/+bug/1701798
          sudo mkdir -p /usr/${{ matrix.config.triple }}/etc
          sudo touch /usr/${{ matrix.config.triple }}/etc/ld.so.cache
      - name: Configure with ${{ matrix.config.triple }}
        run: |
          cmake -S . -B build -G Ninja -DQEMU=ON -DBUILD_TESTING=ON -DCMAKE_C_COMPILER=${{ matrix.config.triple }}-gcc -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE -DCMAKE_INSTALL_PREFIX=$PWD/install
      - name: Build
        run: |
          cmake --build build
          ls -lh build
      - name: Install
        run: |
          cmake --install build
      - name: Modify for qemu
        run: |
          patchelf --set-interpreter /usr/${{ matrix.config.triple}}/lib/ld-linux*.so.* build/uv_run_tests
          patchelf --set-interpreter /usr/${{ matrix.config.triple}}/lib/ld-linux*.so.* build/uv_run_tests_a
          patchelf --add-rpath /usr/${{ matrix.config.triple}}/lib build/uv_run_tests
          patchelf --add-rpath /usr/${{ matrix.config.triple}}/lib build/uv_run_tests_a
      - name: Test
        # Use explicit qemu to test it was compiled for the right arch
        run: |
          qemu-${{ matrix.config.qemu }} --version
          qemu-${{ matrix.config.qemu }} build/uv_run_tests_a
      - name: Test
        if: always()
        run: |
          qemu-${{ matrix.config.qemu }} build/uv_run_tests
