name: release-windows

on:
  release:
    tags:
      - '*'

jobs:
  windows:
    name: windows-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: CMake build
        run: |
             cmake .
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: CMake release
        run: |
             msbuild INSTALL.vcxproj /p:Configuration=Release
      - name: Create binary archive from release
        run: |
             mkdir libuv-${{ github.event.release.tag_name }}\bin
             mkdir libuv-${{ github.event.release.tag_name }}\lib
             move include libuv-${{ github.event.release.tag_name }}\
             move Release/uv.lib libuv-${{ github.event.release.tag_name }}\lib\
             move Release/uv.dll libuv-${{ github.event.release.tag_name }}\bin\
             7z a libuv-${{ github.event.release.tag_name }}.zip libuv-${{ github.event.release.tag_name }}\* -tzip -y
      - name: Upload the windows binary artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libuv-${{ github.event.release.tag_name }}.zip
          asset_name: libuv-${{ github.event.release.tag_name }}-windows
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Windows binary - 'libuv' .dll, .lib, and .h headers."
